# version: "3.8"

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: resume-frontend
#     restart: always
#     ports:
#       - "5173:5173"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: npm run dev -- --host

version: "3.8"

services:
  frontend:
    build: .
    container_name: resume-frontend
    restart: always
    ports:
      - "5173:5173"
